services:
  db:
    image: mysql:9.7.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=symfony_db
  web:
    build: .
    ports:
      - 8080:80